# Generated by Django 5.2.8 on 2025-11-27 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0003_alter_eleves_options_alter_matiere_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eleves',
            options={},
        ),
        migrations.AlterModelOptions(
            name='matiere',
            options={},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='semestre',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='coefficient',
        ),
        migrations.AlterField(
            model_name='eleves',
            name='code_eleve',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='eleves',
            name='nb_absence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eleves',
            name='nb_retard',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='note',
            name='appreciation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='devoir1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='devoir2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleves.eleves'),
        ),
        migrations.AlterField(
            model_name='note',
            name='inter1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='inter2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='inter3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='inter4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='matiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eleves.matiere'),
        ),
        migrations.AlterField(
            model_name='note',
            name='semestre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eleves.semestre'),
        ),
        migrations.AlterField(
            model_name='semestre',
            name='nom',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.RemoveField(
            model_name='semestre',
            name='annee_scolaire',
        ),
    ]
